import { Inter } from "next/font/google";
// import "../../style/main.scss";
import "./globals.css";
import { ThemeProvider } from "@/context/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Multi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          // enableSystem
          // disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
